array(
 'responseHeader'=>array(
  'status'=>0,
  'QTime'=>222),
 'response'=>array('numFound'=>1785,'start'=>0,'maxScore'=>198022.4,'docs'=>array(
	array(
	 'adm1_code'=>'A8',
	 'adm1_name'=>'Région Île-de-France',
	 'adm2_code'=>'75',
	 'adm2_name'=>'Département de Ville-de-Paris',
	 'adm3_code'=>'751',
	 'adm3_name'=>'Arrondissement de Paris',
	 'adm4_code'=>'75056',
	 'adm4_name'=>'Paris',
	 'country_code'=>'FR',
	 'country_flag_url'=>'/images/flags/FR.png',
	 'country_name'=>'France',
	 'feature_class'=>'P',
	 'feature_code'=>'PPLC',
	 'feature_id'=>2988507,
	 'fully_qualified_name'=>'Paris(75000), Département de Ville-de-Paris, Région Île-de-France',
	 'google_map_url'=>'http://maps.google.com/maps?f=q&ie=UTF-8&iwloc=addr&om=1&z=12&q=Paris&ll=48.883408813476564,2.34879994392395',
	 'gtopo30'=>30,
	 'lat'=>48.85340881347656,
	 'lng'=>2.34879994392395,
	 'name'=>'Paris',
	 'name_ascii'=>'Paris',
	 'placetype'=>'City',
	 'population'=>2138551,
	 'timezone'=>'Europe/Paris',
	 'yahoo_map_url'=>'http://maps.yahoo.com/broadband?mag=6&mvt=m&lon=2.34879994392395&lat=48.85340881347656',
	 'zipcode'=>75000,
	 'country_name_alternate_NN'=>array(
	  'Frankrike'),
	 'country_name_alternate_NO'=>array(
	  'Frankrike'),
	 'country_name_alternate_WAR'=>array(
	  'Fransya'),
	 'name_alternate_LT'=>array(
	  'Paryžius'),
	 'name_alternate_LV'=>array(
	  'Parīze'),
	 'country_name_alternate_VEC'=>array(
	  'Franzsa'),
	 'country_name_alternate_NA'=>array(
	  'France'),
	 'country_name_alternate_NE'=>array(
	  'फ्रान्स'),
	 'name_alternate_MR'=>array(
	  'पॅरिस'),
	 'country_name_alternate_CSB'=>array(
	  'Francëjô'),
	 'name_alternate_MS'=>array(
	  'Paris'),
	 'country_name_alternate_NB'=>array(
	  'Frankrike'),
	 'name_alternate_MG'=>array(
	  'Paris'),
	 'country_name_alternate_NL'=>array(
	  'Frankrijk'),
	 'name_alternate_MK'=>array(
	  'Париз'),
	 'country_name_alternate_MN'=>array(
	  'Франц улс',
	  'Франц'),
	 'name_alternate_SCO'=>array(
	  'Paris'),
	 'name_alternate_LB'=>array(
	  'Paräis'),
	 'country_name_alternate_MR'=>array(
	  'फ्रान्स'),
	 'name_alternate_LA'=>array(
	  'Lutetia Parisorum'),
	 'country_name_alternate_MS'=>array(
	  'Perancis'),
	 'name_alternate_SCN'=>array(
	  'Pariggi'),
	 'country_name_alternate_MT'=>array(
	  'Franza'),
	 'name_alternate_KU'=>array(
	  'Parîs'),
	 'name_alternate_KW'=>array(
	  'Paris'),
	 'name_alternate_LN'=>array(
	  'Pari'),
	 'country_name_alternate_TET'=>array(
	  'Fransa'),
	 'country_name_alternate_MG'=>array(
	  'Frantsa'),
	 'name_alternate_LI'=>array(
	  'Paries'),
	 'country_name_alternate_TPI'=>array(
	  'Pranis'),
	 'country_name_alternate_ML'=>array(
	  'ഫ്രാന്‍സ്'),
	 'country_name_alternate_MK'=>array(
	  'Франција'),
	 'name_alternate_OC'=>array(
	  'París'),
	 'country_name_alternate_LN'=>array(
	  'Falansia'),
	 'country_name_alternate_LO'=>array(
	  'ຝລັ່ງ'),
	 'country_name_alternate_PAM'=>array(
	  'France'),
	 'country_name_alternate_LV'=>array(
	  'Francija'),
	 'country_name_alternate_LT'=>array(
	  'Prancūzija'),
	 'name_alternate_OS'=>array(
	  'Париж'),
	 'country_name_alternate_LB'=>array(
	  'Frankräich'),
	 'country_name_alternate_LA'=>array(
	  'Francia',
	  'Francogallia'),
	 'country_name_alternate_LI'=>array(
	  'Frankriek'),
	 'name_alternate_TET'=>array(
	  'París'),
	 'country_name_alternate_KO'=>array(
	  '프랑스'),
	 'name_alternate_NA'=>array(
	  'Paris'),
	 'country_name_alternate_SCO'=>array(
	  'Fraunce'),
	 'country_name_alternate_SCN'=>array(
	  'Francia'),
	 'country_name_alternate_KM'=>array(
	  'បារាំង'),
	 'adm1_name_alternate_FR'=>array(
	  'Île-de-France',
	  'Région parisienne'),
	 'country_name_alternate_KN'=>array(
	  'ಫ್ರಾನ್ಸ್'),
	 'country_name_alternate_KW'=>array(
	  'Pow Frynk'),
	 'country_name_alternate_KS'=>array(
	  'फ्रांस'),
	 'country_name_alternate_UDM'=>array(
	  'Франция'),
	 'country_name_alternate_KU'=>array(
	  'Fransa'),
	 'country_name_alternate_KA'=>array(
	  'საფრანგეთი'),
	 'name_alternate_NO'=>array(
	  'Paris'),
	 'name_alternate_NN'=>array(
	  'Paris'),
	 'name_alternate_NL'=>array(
	  'Parijs'),
	 'name_alternate_HR'=>array(
	  'Pariz'),
	 'country_name_alternate_SA'=>array(
	  'फ्रांस'),
	 'name_alternate_HU'=>array(
	  'Párizs'),
	 'country_name_alternate_RU'=>array(
	  'Франция'),
	 'name_alternate_ALS'=>array(
	  'Paris'),
	 'name_alternate_HY'=>array(
	  'Փարիզ'),
	 'name_alternate_IA'=>array(
	  'Paris'),
	 'country_name_alternate_RM'=>array(
	  'Frantscha'),
	 'name_alternate_ID'=>array(
	  'Paris'),
	 'country_name_alternate_RO'=>array(
	  'Franţa'),
	 'name_alternate_VLS'=>array(
	  'Paris'),
	 'name_alternate_IO'=>array(
	  'Paris'),
	 'name_alternate_GV'=>array(
	  'Paarys'),
	 'country_name_alternate_QU'=>array(
	  'Fransiya',
	  'Fransya'),
	 'name_alternate_HE'=>array(
	  'פריז'),
	 'country_name_alternate_AF'=>array(
	  'Frankryk'),
	 'name_alternate_ZH'=>array(
	  '巴黎'),
	 'country_name_alternate_AA'=>array(
	  'France'),
	 'country_name_alternate_AN'=>array(
	  'Franzia'),
	 'country_name_alternate_AM'=>array(
	  'ፈረንሳይ',
	  'ፈረንሣይ'),
	 'country_name_alternate_PT'=>array(
	  'França'),
	 'name_alternate_KA'=>array(
	  'პარიზი'),
	 'country_name_alternate_PS'=>array(
	  'فرانسه'),
	 'country_name_alternate_PL'=>array(
	  'Francja'),
	 'name_alternate_KO'=>array(
	  '파리 시'),
	 'country_name_alternate_PMS'=>array(
	  'Fransa'),
	 'name_alternate_KN'=>array(
	  'ಪ್ಯಾರಿಸ್'),
	 'country_name_alternate_BG'=>array(
	  'Франция'),
	 'name_alternate_IT'=>array(
	  'Parigi'),
	 'country_name_alternate_BE'=>array(
	  'Францыя'),
	 'name_alternate_IS'=>array(
	  'París'),
	 'name_alternate_PMS'=>array(
	  'Paris'),
	 'country_name_alternate_OS'=>array(
	  'Франц'),
	 'country_name_alternate_BO'=>array(
	  'ཕ་རཱན་སི།'),
	 'country_name_alternate_BN'=>array(
	  'ফ্রান্স'),
	 'country_name_alternate_OM'=>array(
	  'France'),
	 'name_alternate_LMO'=>array(
	  'Paris'),
	 'country_name_alternate_AR'=>array(
	  'فرنسا'),
	 'name_alternate_JA'=>array(
	  'パリ'),
	 'country_name_alternate_OC'=>array(
	  'França'),
	 'country_name_alternate_ILO'=>array(
	  'Francia'),
	 'country_name_alternate_AZ'=>array(
	  'Fransa'),
	 'country_name_alternate_VI'=>array(
	  'Pháp'),
	 'name_alternate_ARC'=>array(
	  'ܦܪܝܣ'),
	 'name_alternate_FA'=>array(
	  'پاریس'),
	 'country_name_alternate_CA'=>array(
	  'França'),
	 'country_name_alternate_VO'=>array(
	  'Fransän'),
	 'country_name_alternate_BS'=>array(
	  'Francuska'),
	 'country_name_alternate_BR'=>array(
	  'Bro-C\'hall'),
	 'name_alternate_UR'=>array(
	  'پیرس'),
	 'country_name_alternate_ARC'=>array(
	  'ܦܪܢܣܐ'),
	 'name_alternate_FI'=>array(
	  'Pariisi'),
	 'name_alternate_UG'=>array(
	  'پارىژ'),
	 'name_alternate_EL'=>array(
	  'Παρίσι'),
	 'name_alternate_EO'=>array(
	  'Parizo'),
	 'name_alternate_EN'=>array(
	  'Paris'),
	 'name_alternate_UK'=>array(
	  'Париж'),
	 'country_name_alternate_CO'=>array(
	  'Francia'),
	 'name_alternate_ES'=>array(
	  'París'),
	 'name_alternate_EU'=>array(
	  'Paris'),
	 'name_alternate_ET'=>array(
	  'Pariis'),
	 'country_name_alternate_UG'=>array(
	  'فرانسىيە'),
	 'name_alternate_GA'=>array(
	  'Páras'),
	 'country_name_alternate_DA'=>array(
	  'Frankrig'),
	 'name_alternate_GD'=>array(
	  'Paris'),
	 'country_name_alternate_UK'=>array(
	  'Франція'),
	 'name_alternate_TY'=>array(
	  'Paris'),
	 'name_alternate_TL'=>array(
	  'Paris',
	  'Lungsod ng Paris'),
	 'country_name_alternate_CS'=>array(
	  'Francie'),
	 'country_name_alternate_CV'=>array(
	  'Франци'),
	 'name_alternate_GL'=>array(
	  'París - Paris'),
	 'country_name_alternate_UR'=>array(
	  'فرانس'),
	 'name_alternate_TR'=>array(
	  'Paris'),
	 'country_name_alternate_CY'=>array(
	  'Ffrainc'),
	 'name_alternate_TH'=>array(
	  'ปารีส'),
	 'name_alternate_TG'=>array(
	  'Париж'),
	 'name_alternate_FR'=>array(
	  'Lutece',
	  'Paname',
	  'Pantruche',
	  'Paris',
	  'Ville-Lumière'),
	 'country_name_alternate_UZ'=>array(
	  'Франция'),
	 'country_name_alternate_DE'=>array(
	  'Frankreich'),
	 'name_alternate_TA'=>array(
	  'பாரிஸ்'),
	 'country_name_alternate_AST'=>array(
	  'Francia'),
	 'name_alternate_FY'=>array(
	  'Parys'),
	 'country_name_alternate_TH'=>array(
	  'ฝรั่งเศส',
	  'ประเทศฝรั่งเศส'),
	 'name_alternate_DA'=>array(
	  'Paris'),
	 'name_alternate_IATA'=>array(
	  'PAR'),
	 'country_name_alternate_TE'=>array(
	  'ఫ్రాన్స్‌'),
	 'country_name_alternate_FUR'=>array(
	  'France'),
	 'country_name_alternate_TG'=>array(
	  'Фаронса'),
	 'country_name_alternate_DZ'=>array(
	  'ཕརཱནསི'),
	 'country_name_alternate_TR'=>array(
	  'Fransa'),
	 'name_alternate_LAD'=>array(
	  'Paris'),
	 'country_name_alternate_DV'=>array(
	  'ފަރަންސޭސިވިލާތް'),
	 'country_name_alternate_TL'=>array(
	  'Pransya'),
	 'country_name_alternate_TO'=>array(
	  'Falanisē'),
	 'name_alternate_DE'=>array(
	  'Paris'),
	 'country_name_alternate_NDS'=>array(
	  'Frankriek'),
	 'country_name_alternate_ES'=>array(
	  'Francia'),
	 'country_name_alternate_ET'=>array(
	  'Prantsusmaa'),
	 'country_name_alternate_TY'=>array(
	  'Farāni'),
	 'country_name_alternate_EO'=>array(
	  'Francio',
	  'Francujo'),
	 'name_alternate_AST'=>array(
	  'París'),
	 'country_name_alternate_EN'=>array(
	  'France'),
	 'country_name_alternate_EL'=>array(
	  'Γαλλία'),
	 'name_alternate_CY'=>array(
	  'Paris'),
	 'name_alternate_CS'=>array(
	  'Paříž'),
	 'country_name_alternate_SH'=>array(
	  'Francuska'),
	 'country_name_alternate_SE'=>array(
	  'Fránkriika'),
	 'country_name_alternate_FA'=>array(
	  'فرانسه'),
	 'country_name_alternate_SC'=>array(
	  'Frantza'),
	 'country_name_alternate_SR'=>array(
	  'Француска'),
	 'country_name_alternate_SQ'=>array(
	  'Francë',
	  'Franca'),
	 'country_name_alternate_SO'=>array(
	  'Faransiis',
	  'Faransiiska'),
	 'country_name_alternate_EU'=>array(
	  'Frantzia'),
	 'country_name_alternate_SL'=>array(
	  'Francija'),
	 'country_name_alternate_SK'=>array(
	  'Francúzsko'),
	 'country_name_alternate_FR'=>array(
	  'République Française',
	  'France'),
	 'country_name_alternate_VLS'=>array(
	  'Vrankriek'),
	 'name_alternate_VI'=>array(
	  'Paris'),
	 'country_name_alternate_SW'=>array(
	  'Ufaransa'),
	 'country_name_alternate_FO'=>array(
	  'Frakland'),
	 'country_name_alternate_SV'=>array(
	  'Frankrike'),
	 'country_name_alternate_ST'=>array(
	  'France'),
	 'country_name_alternate_TA'=>array(
	  'பிரான்ஸ்'),
	 'country_name_alternate_LMO'=>array(
	  'Francja'),
	 'country_name_alternate_FI'=>array(
	  'Ranska'),
	 'country_name_alternate_FY'=>array(
	  'Frankryk'),
	 'name_alternate_BE'=>array(
	  'Парыж'),
	 'name_alternate_BG'=>array(
	  'Париж'),
	 'country_name_alternate_GA'=>array(
	  'An Fhrainc'),
	 'country_name_alternate_ANG'=>array(
	  'Francland'),
	 'country_name_alternate_NRM'=>array(
	  'France'),
	 'country_name_alternate_GD'=>array(
	  'An Fhraing'),
	 'name_alternate_AR'=>array(
	  'باريس'),
	 'country_name_alternate_GL'=>array(
	  'Francia'),
	 'country_name_alternate_HSB'=>array(
	  'Francoska'),
	 'country_name_alternate_KSH'=>array(
	  'Frankrish'),
	 'country_name_alternate_CEB'=>array(
	  'Pransiya'),
	 'country_name_alternate_GV'=>array(
	  'Yn Rank'),
	 'country_name_alternate_GU'=>array(
	  'ફ્રાઁસ'),
	 'name_alternate_AM'=>array(
	  'ፓሪስ'),
	 'name_alternate_AN'=>array(
	  'París'),
	 'name_alternate_PL'=>array(
	  'Paryż'),
	 'country_name_alternate_JBO'=>array(
	  'fasygu\'e'),
	 'name_alternate_PT'=>array(
	  'Paris'),
	 'name_alternate_CA'=>array(
	  'París'),
	 'country_name_alternate_FRP'=>array(
	  'France'),
	 'country_name_alternate_HE'=>array(
	  'צרפת'),
	 'country_name_alternate_CDO'=>array(
	  'Huák-guók'),
	 'country_name_alternate_HI'=>array(
	  'फ्रांस',
	  'फ़्राँस',
	  'फ़्रांस'),
	 'name_alternate_BR'=>array(
	  'Pariz'),
	 'country_name_alternate_ZH'=>array(
	  '法国'),
	 'country_name_alternate_HR'=>array(
	  'Francuska'),
	 'country_name_alternate_HU'=>array(
	  'Franciaország'),
	 'country_name_alternate_HT'=>array(
	  'Frans'),
	 'name_alternate_KSH'=>array(
	  'Paris'),
	 'name_alternate_SQ'=>array(
	  'Paris',
	  'Parisi'),
	 'name_alternate_SL'=>array(
	  'Pariz'),
	 'name_alternate_SK'=>array(
	  'Paríž'),
	 'country_name_alternate_HY'=>array(
	  'Ֆրանսիա'),
	 'name_alternate_NDS'=>array(
	  'Paris'),
	 'name_alternate_SW'=>array(
	  'Paris'),
	 'name_alternate_SV'=>array(
	  'Paris'),
	 'country_name_alternate_ID'=>array(
	  'Perancis',
	  'Prancis'),
	 'country_name_alternate_IA'=>array(
	  'Francia'),
	 'name_alternate_SR'=>array(
	  'Париз'),
	 'country_name_alternate_IO'=>array(
	  'Francia'),
	 'country_name_alternate_LAD'=>array(
	  'Fransia'),
	 'country_name_alternate_NOV'=>array(
	  'Fransia'),
	 'country_name_alternate_II'=>array(
	  'ꃔꇩ'),
	 'country_name_alternate_RMY'=>array(
	  'Franchiya'),
	 'country_name_alternate_IT'=>array(
	  'Francia'),
	 'country_name_alternate_IS'=>array(
	  'Frakkland'),
	 'name_alternate_AF'=>array(
	  'Parys'),
	 'name_alternate_RO'=>array(
	  'Paris'),
	 'country_name_alternate_JA'=>array(
	  'フランス',
	  'フランス共和国'),
	 'country_name_alternate_BAR'=>array(
	  'Frankreich'),
	 'name_alternate_RU'=>array(
	  'Париж'),
	 'score'=>198022.4),
	array(
	 'country_code'=>'FR',
	 'country_flag_url'=>'/images/flags/FR.png',
	 'country_name'=>'France',
	 'feature_class'=>'A',
	 'feature_code'=>'ADM2',
	 'feature_id'=>2968815,
	 'fully_qualified_name'=>'Département de Ville-de-Paris, Département de Ville-de-Paris, Région Île-de-France',
	 'google_map_url'=>'http://maps.google.com/maps?f=q&ie=UTF-8&iwloc=addr&om=1&z=12&q=D%C3%A9partement+de+Ville-de-Paris&ll=48.8834049987793,2.3485984802246094',
	 'gtopo30'=>30,
	 'lat'=>48.8534049987793,
	 'lng'=>2.3485984802246094,
	 'name'=>'Département de Ville-de-Paris',
	 'name_ascii'=>'Departement de Ville-de-Paris',
	 'placetype'=>'Adm',
	 'population'=>2138551,
	 'timezone'=>'Europe/Paris',
	 'yahoo_map_url'=>'http://maps.yahoo.com/broadband?mag=6&mvt=m&lon=2.3485984802246094&lat=48.8534049987793',
	 'country_name_alternate_VI'=>array(
	  'Pháp'),
	 'country_name_alternate_NN'=>array(
	  'Frankrike'),
	 'country_name_alternate_NO'=>array(
	  'Frankrike'),
	 'country_name_alternate_WAR'=>array(
	  'Fransya'),
	 'country_name_alternate_CA'=>array(
	  'França'),
	 'country_name_alternate_VO'=>array(
	  'Fransän'),
	 'country_name_alternate_BS'=>array(
	  'Francuska'),
	 'country_name_alternate_BR'=>array(
	  'Bro-C\'hall'),
	 'country_name_alternate_ARC'=>array(
	  'ܦܪܢܣܐ'),
	 'country_name_alternate_VEC'=>array(
	  'Franzsa'),
	 'country_name_alternate_NA'=>array(
	  'France'),
	 'country_name_alternate_NE'=>array(
	  'फ्रान्स'),
	 'name_alternate_ES'=>array(
	  'Paris'),
	 'country_name_alternate_CO'=>array(
	  'Francia'),
	 'country_name_alternate_CSB'=>array(
	  'Francëjô'),
	 'country_name_alternate_NB'=>array(
	  'Frankrike'),
	 'country_name_alternate_NL'=>array(
	  'Frankrijk'),
	 'country_name_alternate_UG'=>array(
	  'فرانسىيە'),
	 'country_name_alternate_MN'=>array(
	  'Франц улс',
	  'Франц'),
	 'country_name_alternate_DA'=>array(
	  'Frankrig'),
	 'country_name_alternate_UK'=>array(
	  'Франція'),
	 'country_name_alternate_MR'=>array(
	  'फ्रान्स'),
	 'country_name_alternate_MS'=>array(
	  'Perancis'),
	 'country_name_alternate_MT'=>array(
	  'Franza'),
	 'country_name_alternate_CS'=>array(
	  'Francie'),
	 'country_name_alternate_CV'=>array(
	  'Франци'),
	 'country_name_alternate_UR'=>array(
	  'فرانس'),
	 'country_name_alternate_CY'=>array(
	  'Ffrainc'),
	 'country_name_alternate_TET'=>array(
	  'Fransa'),
	 'name_alternate_FR'=>array(
	  'Paris'),
	 'country_name_alternate_UZ'=>array(
	  'Франция'),
	 'country_name_alternate_DE'=>array(
	  'Frankreich'),
	 'country_name_alternate_MG'=>array(
	  'Frantsa'),
	 'country_name_alternate_TPI'=>array(
	  'Pranis'),
	 'country_name_alternate_ML'=>array(
	  'ഫ്രാന്‍സ്'),
	 'country_name_alternate_AST'=>array(
	  'Francia'),
	 'country_name_alternate_MK'=>array(
	  'Франција'),
	 'country_name_alternate_TH'=>array(
	  'ฝรั่งเศส',
	  'ประเทศฝรั่งเศส'),
	 'country_name_alternate_TE'=>array(
	  'ఫ్రాన్స్‌'),
	 'country_name_alternate_LN'=>array(
	  'Falansia'),
	 'country_name_alternate_FUR'=>array(
	  'France'),
	 'country_name_alternate_LO'=>array(
	  'ຝລັ່ງ'),
	 'country_name_alternate_TG'=>array(
	  'Фаронса'),
	 'country_name_alternate_PAM'=>array(
	  'France'),
	 'country_name_alternate_DZ'=>array(
	  'ཕརཱནསི'),
	 'country_name_alternate_TR'=>array(
	  'Fransa'),
	 'country_name_alternate_LV'=>array(
	  'Francija'),
	 'country_name_alternate_TL'=>array(
	  'Pransya'),
	 'country_name_alternate_DV'=>array(
	  'ފަރަންސޭސިވިލާތް'),
	 'country_name_alternate_TO'=>array(
	  'Falanisē'),
	 'country_name_alternate_LT'=>array(
	  'Prancūzija'),
	 'country_name_alternate_ES'=>array(
	  'Francia'),
	 'country_name_alternate_NDS'=>array(
	  'Frankriek'),
	 'country_name_alternate_TY'=>array(
	  'Farāni'),
	 'country_name_alternate_ET'=>array(
	  'Prantsusmaa'),
	 'country_name_alternate_LB'=>array(
	  'Frankräich'),
	 'country_name_alternate_LA'=>array(
	  'Francia',
	  'Francogallia'),
	 'country_name_alternate_EO'=>array(
	  'Francio',
	  'Francujo'),
	 'country_name_alternate_EN'=>array(
	  'France'),
	 'country_name_alternate_EL'=>array(
	  'Γαλλία'),
	 'country_name_alternate_LI'=>array(
	  'Frankriek'),
	 'country_name_alternate_KO'=>array(
	  '프랑스'),
	 'country_name_alternate_SH'=>array(
	  'Francuska'),
	 'country_name_alternate_SCO'=>array(
	  'Fraunce'),
	 'country_name_alternate_SE'=>array(
	  'Fránkriika'),
	 'country_name_alternate_SCN'=>array(
	  'Francia'),
	 'country_name_alternate_FA'=>array(
	  'فرانسه'),
	 'country_name_alternate_KM'=>array(
	  'បារាំង'),
	 'country_name_alternate_SC'=>array(
	  'Frantza'),
	 'country_name_alternate_KN'=>array(
	  'ಫ್ರಾನ್ಸ್'),
	 'country_name_alternate_SR'=>array(
	  'Француска'),
	 'country_name_alternate_KW'=>array(
	  'Pow Frynk'),
	 'country_name_alternate_SQ'=>array(
	  'Francë',
	  'Franca'),
	 'country_name_alternate_SO'=>array(
	  'Faransiis',
	  'Faransiiska'),
	 'country_name_alternate_KS'=>array(
	  'फ्रांस'),
	 'country_name_alternate_UDM'=>array(
	  'Франция'),
	 'country_name_alternate_EU'=>array(
	  'Frantzia'),
	 'country_name_alternate_SL'=>array(
	  'Francija'),
	 'country_name_alternate_KU'=>array(
	  'Fransa'),
	 'country_name_alternate_SK'=>array(
	  'Francúzsko'),
	 'country_name_alternate_VLS'=>array(
	  'Vrankriek'),
	 'country_name_alternate_FR'=>array(
	  'République Française',
	  'France'),
	 'country_name_alternate_SW'=>array(
	  'Ufaransa'),
	 'country_name_alternate_KA'=>array(
	  'საფრანგეთი'),
	 'country_name_alternate_SV'=>array(
	  'Frankrike'),
	 'country_name_alternate_FO'=>array(
	  'Frakland'),
	 'country_name_alternate_ST'=>array(
	  'France'),
	 'country_name_alternate_TA'=>array(
	  'பிரான்ஸ்'),
	 'country_name_alternate_FI'=>array(
	  'Ranska'),
	 'country_name_alternate_LMO'=>array(
	  'Francja'),
	 'country_name_alternate_FY'=>array(
	  'Frankryk'),
	 'country_name_alternate_SA'=>array(
	  'फ्रांस'),
	 'country_name_alternate_RU'=>array(
	  'Франция'),
	 'country_name_alternate_GA'=>array(
	  'An Fhrainc'),
	 'country_name_alternate_ANG'=>array(
	  'Francland'),
	 'country_name_alternate_NRM'=>array(
	  'France'),
	 'country_name_alternate_GD'=>array(
	  'An Fhraing'),
	 'country_name_alternate_RM'=>array(
	  'Frantscha'),
	 'country_name_alternate_GL'=>array(
	  'Francia'),
	 'country_name_alternate_RO'=>array(
	  'Franţa'),
	 'country_name_alternate_HSB'=>array(
	  'Francoska'),
	 'country_name_alternate_KSH'=>array(
	  'Frankrish'),
	 'country_name_alternate_GV'=>array(
	  'Yn Rank'),
	 'country_name_alternate_CEB'=>array(
	  'Pransiya'),
	 'country_name_alternate_GU'=>array(
	  'ફ્રાઁસ'),
	 'country_name_alternate_JBO'=>array(
	  'fasygu\'e'),
	 'country_name_alternate_QU'=>array(
	  'Fransiya',
	  'Fransya'),
	 'country_name_alternate_HE'=>array(
	  'צרפת'),
	 'country_name_alternate_FRP'=>array(
	  'France'),
	 'country_name_alternate_HI'=>array(
	  'फ्रांस',
	  'फ़्राँस',
	  'फ़्रांस'),
	 'country_name_alternate_CDO'=>array(
	  'Huák-guók'),
	 'country_name_alternate_ZH'=>array(
	  '法国'),
	 'country_name_alternate_HR'=>array(
	  'Francuska'),
	 'country_name_alternate_HU'=>array(
	  'Franciaország'),
	 'country_name_alternate_HT'=>array(
	  'Frans'),
	 'country_name_alternate_AF'=>array(
	  'Frankryk'),
	 'country_name_alternate_AA'=>array(
	  'France'),
	 'country_name_alternate_HY'=>array(
	  'Ֆրանսիա'),
	 'country_name_alternate_AN'=>array(
	  'Franzia'),
	 'country_name_alternate_AM'=>array(
	  'ፈረንሳይ',
	  'ፈረንሣይ'),
	 'country_name_alternate_PT'=>array(
	  'França'),
	 'country_name_alternate_PS'=>array(
	  'فرانسه'),
	 'country_name_alternate_ID'=>array(
	  'Perancis',
	  'Prancis'),
	 'country_name_alternate_IA'=>array(
	  'Francia'),
	 'country_name_alternate_IO'=>array(
	  'Francia'),
	 'country_name_alternate_PL'=>array(
	  'Francja'),
	 'country_name_alternate_LAD'=>array(
	  'Fransia'),
	 'country_name_alternate_II'=>array(
	  'ꃔꇩ'),
	 'country_name_alternate_NOV'=>array(
	  'Fransia'),
	 'country_name_alternate_PMS'=>array(
	  'Fransa'),
	 'country_name_alternate_RMY'=>array(
	  'Franchiya'),
	 'country_name_alternate_IT'=>array(
	  'Francia'),
	 'country_name_alternate_IS'=>array(
	  'Frakkland'),
	 'name_alternate_IT'=>array(
	  'Parigi'),
	 'country_name_alternate_BG'=>array(
	  'Франция'),
	 'country_name_alternate_JA'=>array(
	  'フランス',
	  'フランス共和国'),
	 'country_name_alternate_BE'=>array(
	  'Францыя'),
	 'country_name_alternate_BAR'=>array(
	  'Frankreich'),
	 'country_name_alternate_OS'=>array(
	  'Франц'),
	 'country_name_alternate_BO'=>array(
	  'ཕ་རཱན་སི།'),
	 'country_name_alternate_BN'=>array(
	  'ফ্রান্স'),
	 'country_name_alternate_OM'=>array(
	  'France'),
	 'country_name_alternate_AR'=>array(
	  'فرنسا'),
	 'country_name_alternate_OC'=>array(
	  'França'),
	 'country_name_alternate_ILO'=>array(
	  'Francia'),
	 'country_name_alternate_AZ'=>array(
	  'Fransa'),
	 'score'=>198019.3),
	array(
	 'adm1_code'=>'TX',
	 'adm1_name'=>'Texas',
	 'adm2_code'=>'277',
	 'adm2_name'=>'Lamar County',
	 'country_code'=>'US',
	 'country_flag_url'=>'/images/flags/US.png',
	 'country_name'=>'United States',
	 'elevation'=>183,
	 'feature_class'=>'P',
	 'feature_code'=>'PPL',
	 'feature_id'=>4717560,
	 'fully_qualified_name'=>'Paris, Lamar County, Texas',
	 'google_map_url'=>'http://maps.google.com/maps?f=q&ie=UTF-8&iwloc=addr&om=1&z=12&q=Paris&ll=33.690938262939454,-95.55551147460938',
	 'gtopo30'=>182,
	 'lat'=>33.66093826293945,
	 'lng'=>-95.55551147460938,
	 'name'=>'Paris',
	 'name_ascii'=>'Paris',
	 'placetype'=>'City',
	 'population'=>27022,
	 'timezone'=>'America/Chicago',
	 'yahoo_map_url'=>'http://maps.yahoo.com/broadband?mag=6&mvt=m&lon=-95.55551147460938&lat=33.66093826293945',
	 'score'=>2511.9224),
	array(
	 'adm1_code'=>'TN',
	 'adm1_name'=>'Tennessee',
	 'adm2_code'=>'079',
	 'adm2_name'=>'Henry County',
	 'country_code'=>'US',
	 'country_flag_url'=>'/images/flags/US.png',
	 'country_name'=>'United States',
	 'elevation'=>157,
	 'feature_class'=>'P',
	 'feature_code'=>'PPL',
	 'feature_id'=>4647963,
	 'fully_qualified_name'=>'Paris, Henry County, Tennessee',
	 'google_map_url'=>'http://maps.google.com/maps?f=q&ie=UTF-8&iwloc=addr&om=1&z=12&q=Paris&ll=36.332001953125,-88.32671356201172',
	 'gtopo30'=>152,
	 'lat'=>36.302001953125,
	 'lng'=>-88.32671356201172,
	 'name'=>'Paris',
	 'name_ascii'=>'Paris',
	 'placetype'=>'City',
	 'population'=>9587,
	 'timezone'=>'America/Indiana/Knox',
	 'yahoo_map_url'=>'http://maps.yahoo.com/broadband?mag=6&mvt=m&lon=-88.32671356201172&lat=36.302001953125',
	 'score'=>897.56726),
	array(
	 'adm1_code'=>'KY',
	 'adm1_name'=>'Kentucky',
	 'adm2_code'=>'017',
	 'adm2_name'=>'Bourbon County',
	 'country_code'=>'US',
	 'country_flag_url'=>'/images/flags/US.png',
	 'country_name'=>'United States',
	 'elevation'=>257,
	 'feature_class'=>'P',
	 'feature_code'=>'PPL',
	 'feature_id'=>4303602,
	 'fully_qualified_name'=>'Paris, Bourbon County, Kentucky',
	 'google_map_url'=>'http://maps.google.com/maps?f=q&ie=UTF-8&iwloc=addr&om=1&z=12&q=Paris&ll=38.23979690551758,-84.25298309326172',
	 'gtopo30'=>244,
	 'lat'=>38.20979690551758,
	 'lng'=>-84.25298309326172,
	 'name'=>'Paris',
	 'name_ascii'=>'Paris',
	 'placetype'=>'City',
	 'population'=>9332,
	 'timezone'=>'America/Indiana/Vevay',
	 'yahoo_map_url'=>'http://maps.yahoo.com/broadband?mag=6&mvt=m&lon=-84.25298309326172&lat=38.20979690551758',
	 'score'=>873.9561),
	array(
	 'adm1_code'=>'IL',
	 'adm1_name'=>'Illinois',
	 'adm2_code'=>'045',
	 'adm2_name'=>'Edgar County',
	 'country_code'=>'US',
	 'country_flag_url'=>'/images/flags/US.png',
	 'country_name'=>'United States',
	 'elevation'=>220,
	 'feature_class'=>'P',
	 'feature_code'=>'PPL',
	 'feature_id'=>4246659,
	 'fully_qualified_name'=>'Paris, Edgar County, Illinois',
	 'google_map_url'=>'http://maps.google.com/maps?f=q&ie=UTF-8&iwloc=addr&om=1&z=12&q=Paris&ll=39.64114501953125,-87.69613647460938',
	 'gtopo30'=>0,
	 'lat'=>39.61114501953125,
	 'lng'=>-87.69613647460938,
	 'name'=>'Paris',
	 'name_ascii'=>'Paris',
	 'placetype'=>'City',
	 'population'=>8875,
	 'timezone'=>'America/Indiana/Knox',
	 'yahoo_map_url'=>'http://maps.yahoo.com/broadband?mag=6&mvt=m&lon=-87.69613647460938&lat=39.61114501953125',
	 'score'=>831.6412),
	array(
	 'adm1_code'=>'B4',
	 'adm1_name'=>'Région Nord-Pas-de-Calais',
	 'adm2_code'=>'62',
	 'adm2_name'=>'Département du Pas-de-Calais',
	 'adm3_code'=>'624',
	 'adm3_name'=>'Arrondissement de Montreuil',
	 'adm4_code'=>'62826',
	 'adm4_name'=>'Le Touquet-Paris-Plage',
	 'country_code'=>'FR',
	 'country_flag_url'=>'/images/flags/FR.png',
	 'country_name'=>'France',
	 'feature_class'=>'P',
	 'feature_code'=>'PPL',
	 'feature_id'=>2999139,
	 'fully_qualified_name'=>'Le Touquet-Paris-Plage(62520), Département du Pas-de-Calais, Région Nord-Pas-de-Calais',
	 'google_map_url'=>'http://maps.google.com/maps?f=q&ie=UTF-8&iwloc=addr&om=1&z=12&q=Le+Touquet-Paris-Plage&ll=50.54666641235352,1.5833332538604736',
	 'gtopo30'=>-9999,
	 'lat'=>50.516666412353516,
	 'lng'=>1.5833332538604736,
	 'name'=>'Le Touquet-Paris-Plage',
	 'name_ascii'=>'Le Touquet-Paris-Plage',
	 'placetype'=>'City',
	 'population'=>5696,
	 'timezone'=>'Europe/Paris',
	 'yahoo_map_url'=>'http://maps.yahoo.com/broadband?mag=6&mvt=m&lon=1.5833332538604736&lat=50.516666412353516',
	 'zipcode'=>62520,
	 'country_name_alternate_VI'=>array(
	  'Pháp'),
	 'country_name_alternate_NN'=>array(
	  'Frankrike'),
	 'country_name_alternate_NO'=>array(
	  'Frankrike'),
	 'country_name_alternate_WAR'=>array(
	  'Fransya'),
	 'country_name_alternate_CA'=>array(
	  'França'),
	 'country_name_alternate_VO'=>array(
	  'Fransän'),
	 'country_name_alternate_BS'=>array(
	  'Francuska'),
	 'country_name_alternate_BR'=>array(
	  'Bro-C\'hall'),
	 'country_name_alternate_ARC'=>array(
	  'ܦܪܢܣܐ'),
	 'country_name_alternate_VEC'=>array(
	  'Franzsa'),
	 'country_name_alternate_NA'=>array(
	  'France'),
	 'country_name_alternate_NE'=>array(
	  'फ्रान्स'),
	 'country_name_alternate_CO'=>array(
	  'Francia'),
	 'country_name_alternate_CSB'=>array(
	  'Francëjô'),
	 'country_name_alternate_NB'=>array(
	  'Frankrike'),
	 'country_name_alternate_NL'=>array(
	  'Frankrijk'),
	 'country_name_alternate_UG'=>array(
	  'فرانسىيە'),
	 'country_name_alternate_MN'=>array(
	  'Франц улс',
	  'Франц'),
	 'country_name_alternate_DA'=>array(
	  'Frankrig'),
	 'country_name_alternate_UK'=>array(
	  'Франція'),
	 'country_name_alternate_MR'=>array(
	  'फ्रान्स'),
	 'country_name_alternate_MS'=>array(
	  'Perancis'),
	 'country_name_alternate_MT'=>array(
	  'Franza'),
	 'country_name_alternate_CS'=>array(
	  'Francie'),
	 'country_name_alternate_CV'=>array(
	  'Франци'),
	 'country_name_alternate_UR'=>array(
	  'فرانس'),
	 'country_name_alternate_CY'=>array(
	  'Ffrainc'),
	 'country_name_alternate_TET'=>array(
	  'Fransa'),
	 'country_name_alternate_UZ'=>array(
	  'Франция'),
	 'country_name_alternate_DE'=>array(
	  'Frankreich'),
	 'country_name_alternate_MG'=>array(
	  'Frantsa'),
	 'country_name_alternate_TPI'=>array(
	  'Pranis'),
	 'country_name_alternate_ML'=>array(
	  'ഫ്രാന്‍സ്'),
	 'country_name_alternate_AST'=>array(
	  'Francia'),
	 'country_name_alternate_MK'=>array(
	  'Франција'),
	 'country_name_alternate_TH'=>array(
	  'ฝรั่งเศส',
	  'ประเทศฝรั่งเศส'),
	 'country_name_alternate_TE'=>array(
	  'ఫ్రాన్స్‌'),
	 'country_name_alternate_LN'=>array(
	  'Falansia'),
	 'country_name_alternate_FUR'=>array(
	  'France'),
	 'country_name_alternate_LO'=>array(
	  'ຝລັ່ງ'),
	 'country_name_alternate_TG'=>array(
	  'Фаронса'),
	 'country_name_alternate_PAM'=>array(
	  'France'),
	 'country_name_alternate_DZ'=>array(
	  'ཕརཱནསི'),
	 'country_name_alternate_TR'=>array(
	  'Fransa'),
	 'country_name_alternate_LV'=>array(
	  'Francija'),
	 'country_name_alternate_TL'=>array(
	  'Pransya'),
	 'country_name_alternate_DV'=>array(
	  'ފަރަންސޭސިވިލާތް'),
	 'country_name_alternate_TO'=>array(
	  'Falanisē'),
	 'country_name_alternate_LT'=>array(
	  'Prancūzija'),
	 'country_name_alternate_ES'=>array(
	  'Francia'),
	 'country_name_alternate_NDS'=>array(
	  'Frankriek'),
	 'country_name_alternate_TY'=>array(
	  'Farāni'),
	 'country_name_alternate_ET'=>array(
	  'Prantsusmaa'),
	 'country_name_alternate_LB'=>array(
	  'Frankräich'),
	 'country_name_alternate_LA'=>array(
	  'Francia',
	  'Francogallia'),
	 'country_name_alternate_EO'=>array(
	  'Francio',
	  'Francujo'),
	 'country_name_alternate_EN'=>array(
	  'France'),
	 'country_name_alternate_EL'=>array(
	  'Γαλλία'),
	 'country_name_alternate_LI'=>array(
	  'Frankriek'),
	 'country_name_alternate_KO'=>array(
	  '프랑스'),
	 'country_name_alternate_SH'=>array(
	  'Francuska'),
	 'country_name_alternate_SCO'=>array(
	  'Fraunce'),
	 'country_name_alternate_SE'=>array(
	  'Fránkriika'),
	 'country_name_alternate_SCN'=>array(
	  'Francia'),
	 'country_name_alternate_FA'=>array(
	  'فرانسه'),
	 'country_name_alternate_KM'=>array(
	  'បារាំង'),
	 'country_name_alternate_SC'=>array(
	  'Frantza'),
	 'country_name_alternate_KN'=>array(
	  'ಫ್ರಾನ್ಸ್'),
	 'country_name_alternate_SR'=>array(
	  'Француска'),
	 'country_name_alternate_KW'=>array(
	  'Pow Frynk'),
	 'country_name_alternate_SQ'=>array(
	  'Francë',
	  'Franca'),
	 'country_name_alternate_SO'=>array(
	  'Faransiis',
	  'Faransiiska'),
	 'country_name_alternate_KS'=>array(
	  'फ्रांस'),
	 'country_name_alternate_UDM'=>array(
	  'Франция'),
	 'country_name_alternate_EU'=>array(
	  'Frantzia'),
	 'country_name_alternate_SL'=>array(
	  'Francija'),
	 'country_name_alternate_KU'=>array(
	  'Fransa'),
	 'country_name_alternate_SK'=>array(
	  'Francúzsko'),
	 'country_name_alternate_VLS'=>array(
	  'Vrankriek'),
	 'country_name_alternate_FR'=>array(
	  'République Française',
	  'France'),
	 'country_name_alternate_SW'=>array(
	  'Ufaransa'),
	 'country_name_alternate_KA'=>array(
	  'საფრანგეთი'),
	 'country_name_alternate_SV'=>array(
	  'Frankrike'),
	 'country_name_alternate_FO'=>array(
	  'Frakland'),
	 'country_name_alternate_ST'=>array(
	  'France'),
	 'country_name_alternate_TA'=>array(
	  'பிரான்ஸ்'),
	 'country_name_alternate_FI'=>array(
	  'Ranska'),
	 'country_name_alternate_LMO'=>array(
	  'Francja'),
	 'country_name_alternate_FY'=>array(
	  'Frankryk'),
	 'country_name_alternate_SA'=>array(
	  'फ्रांस'),
	 'country_name_alternate_RU'=>array(
	  'Франция'),
	 'country_name_alternate_GA'=>array(
	  'An Fhrainc'),
	 'country_name_alternate_ANG'=>array(
	  'Francland'),
	 'country_name_alternate_NRM'=>array(
	  'France'),
	 'country_name_alternate_GD'=>array(
	  'An Fhraing'),
	 'country_name_alternate_RM'=>array(
	  'Frantscha'),
	 'country_name_alternate_GL'=>array(
	  'Francia'),
	 'country_name_alternate_RO'=>array(
	  'Franţa'),
	 'country_name_alternate_HSB'=>array(
	  'Francoska'),
	 'country_name_alternate_KSH'=>array(
	  'Frankrish'),
	 'country_name_alternate_GV'=>array(
	  'Yn Rank'),
	 'country_name_alternate_CEB'=>array(
	  'Pransiya'),
	 'country_name_alternate_GU'=>array(
	  'ફ્રાઁસ'),
	 'country_name_alternate_JBO'=>array(
	  'fasygu\'e'),
	 'country_name_alternate_QU'=>array(
	  'Fransiya',
	  'Fransya'),
	 'country_name_alternate_HE'=>array(
	  'צרפת'),
	 'country_name_alternate_FRP'=>array(
	  'France'),
	 'country_name_alternate_HI'=>array(
	  'फ्रांस',
	  'फ़्राँस',
	  'फ़्रांस'),
	 'country_name_alternate_CDO'=>array(
	  'Huák-guók'),
	 'country_name_alternate_ZH'=>array(
	  '法国'),
	 'country_name_alternate_HR'=>array(
	  'Francuska'),
	 'country_name_alternate_HU'=>array(
	  'Franciaország'),
	 'country_name_alternate_HT'=>array(
	  'Frans'),
	 'country_name_alternate_AF'=>array(
	  'Frankryk'),
	 'country_name_alternate_AA'=>array(
	  'France'),
	 'country_name_alternate_HY'=>array(
	  'Ֆրանսիա'),
	 'country_name_alternate_AN'=>array(
	  'Franzia'),
	 'country_name_alternate_AM'=>array(
	  'ፈረንሳይ',
	  'ፈረንሣይ'),
	 'country_name_alternate_PT'=>array(
	  'França'),
	 'country_name_alternate_PS'=>array(
	  'فرانسه'),
	 'country_name_alternate_ID'=>array(
	  'Perancis',
	  'Prancis'),
	 'country_name_alternate_IA'=>array(
	  'Francia'),
	 'country_name_alternate_IO'=>array(
	  'Francia'),
	 'country_name_alternate_PL'=>array(
	  'Francja'),
	 'country_name_alternate_LAD'=>array(
	  'Fransia'),
	 'country_name_alternate_II'=>array(
	  'ꃔꇩ'),
	 'country_name_alternate_NOV'=>array(
	  'Fransia'),
	 'country_name_alternate_PMS'=>array(
	  'Fransa'),
	 'country_name_alternate_RMY'=>array(
	  'Franchiya'),
	 'country_name_alternate_IT'=>array(
	  'Francia'),
	 'country_name_alternate_IS'=>array(
	  'Frakkland'),
	 'country_name_alternate_BG'=>array(
	  'Франция'),
	 'country_name_alternate_JA'=>array(
	  'フランス',
	  'フランス共和国'),
	 'country_name_alternate_BE'=>array(
	  'Францыя'),
	 'country_name_alternate_BAR'=>array(
	  'Frankreich'),
	 'country_name_alternate_OS'=>array(
	  'Франц'),
	 'country_name_alternate_BO'=>array(
	  'ཕ་རཱན་སི།'),
	 'country_name_alternate_BN'=>array(
	  'ফ্রান্স'),
	 'country_name_alternate_OM'=>array(
	  'France'),
	 'country_name_alternate_AR'=>array(
	  'فرنسا'),
	 'country_name_alternate_OC'=>array(
	  'França'),
	 'country_name_alternate_ILO'=>array(
	  'Francia'),
	 'country_name_alternate_AZ'=>array(
	  'Fransa'),
	 'score'=>532.3486),
	array(
	 'adm1_code'=>'ME',
	 'adm1_name'=>'Maine',
	 'adm2_code'=>'017',
	 'adm2_name'=>'Oxford County',
	 'country_code'=>'US',
	 'country_flag_url'=>'/images/flags/US.png',
	 'country_name'=>'United States',
	 'elevation'=>247,
	 'feature_class'=>'P',
	 'feature_code'=>'PPL',
	 'feature_id'=>4974617,
	 'fully_qualified_name'=>'Paris, Oxford County, Maine',
	 'google_map_url'=>'http://maps.google.com/maps?f=q&ie=UTF-8&iwloc=addr&om=1&z=12&q=Paris&ll=44.28979232788086,-70.50061798095703',
	 'gtopo30'=>230,
	 'lat'=>44.25979232788086,
	 'lng'=>-70.50061798095703,
	 'name'=>'Paris',
	 'name_ascii'=>'Paris',
	 'placetype'=>'City',
	 'population'=>5073,
	 'timezone'=>'America/New_York',
	 'yahoo_map_url'=>'http://maps.yahoo.com/broadband?mag=6&mvt=m&lon=-70.50061798095703&lat=44.25979232788086',
	 'score'=>479.6035),
	array(
	 'adm1_code'=>'AR',
	 'adm1_name'=>'Arkansas',
	 'adm2_code'=>'083',
	 'adm2_name'=>'Logan County',
	 'country_code'=>'US',
	 'country_flag_url'=>'/images/flags/US.png',
	 'country_name'=>'United States',
	 'elevation'=>123,
	 'feature_class'=>'P',
	 'feature_code'=>'PPL',
	 'feature_id'=>4125402,
	 'fully_qualified_name'=>'Paris, Logan County, Arkansas',
	 'google_map_url'=>'http://maps.google.com/maps?f=q&ie=UTF-8&iwloc=addr&om=1&z=12&q=Paris&ll=35.32203414916992,-93.72991943359375',
	 'gtopo30'=>139,
	 'lat'=>35.29203414916992,
	 'lng'=>-93.72991943359375,
	 'name'=>'Paris',
	 'name_ascii'=>'Paris',
	 'placetype'=>'City',
	 'population'=>3689,
	 'timezone'=>'America/Chicago',
	 'yahoo_map_url'=>'http://maps.yahoo.com/broadband?mag=6&mvt=m&lon=-93.72991943359375&lat=35.29203414916992',
	 'score'=>351.45508),
	array(
	 'adm1_code'=>'ME',
	 'adm1_name'=>'Maine',
	 'adm2_code'=>'017',
	 'adm2_name'=>'Oxford County',
	 'country_code'=>'US',
	 'country_flag_url'=>'/images/flags/US.png',
	 'country_name'=>'United States',
	 'elevation'=>118,
	 'feature_class'=>'P',
	 'feature_code'=>'PPL',
	 'feature_id'=>4979220,
	 'fully_qualified_name'=>'South Paris, Oxford County, Maine',
	 'google_map_url'=>'http://maps.google.com/maps?f=q&ie=UTF-8&iwloc=addr&om=1&z=12&q=South+Paris&ll=44.253682403564454,-70.51338958740234',
	 'gtopo30'=>122,
	 'lat'=>44.22368240356445,
	 'lng'=>-70.51338958740234,
	 'name'=>'South Paris',
	 'name_ascii'=>'South Paris',
	 'placetype'=>'City',
	 'population'=>2250,
	 'timezone'=>'America/New_York',
	 'yahoo_map_url'=>'http://maps.yahoo.com/broadband?mag=6&mvt=m&lon=-70.51338958740234&lat=44.22368240356445',
	 'score'=>215.31923))
 ))