  <!-- start footer-->
      </div>
    </div>
    <div class="clear">
      <hr/>
    </div>
    <div id="footer">
      <div class="xright"> Gisgraphy&nbsp;    
  

  
    
  
  
  | Logo by <a href="http://www.icondrawer.com/">icondrawer</div>
      <div class="clear">
        <hr/>
      </div>
      <div id="logos">
		<a href="http://maven.apache.org/"><img src="/images/externallogos/maven.png" alt="Maven 2" class="logo"/></a>
		<a href="http://springframework.org/"><img src="/images/externallogos/spring25.png" alt="Spring Framework" class="logo"/></a>
		<a href="http://www.hibernate.org/" target="_blank"><img src="/images/externallogos/hibernate.png" alt="hibernate" class="logo"/></a>
		<a href="http://www.postgresql.org/"><img src="/images/externallogos/postgres.gif" alt="postgres" class="logo"></a>
		<a href="http://postgis.refractions.net/"><img src="/images/externallogos/postgis.jpg" alt="postgis" class="logo"></a>
		<a href="http://struts.apache.org/2.x/index.html/"><img src="/images/externallogos/struts2.png" class="logo"/></a>
		<a href="http://lucene.apache.org/solr/"><img src="/images/externallogos/solr.png" alt="Solr" class="logo"></a>
		<a href="http://lucene.apache.org/java/docs/index.html"><img src="/images/externallogos/lucene.gif" alt="Lucene" class="logo"></a>
		<a href="http://appfuse.org/"><img src="/images/externallogos/appfuse.gif" class="logo"/></a>
	</div>
    </div>
  <script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-1919557-2");
pageTracker._trackPageview();
</script>
  </body>
</html>